In [2]:
import numpy as np

def is_diagonally_dominant(A): #define the diagonal check function
    A = np.array(A)
    n = A.shape[0]

    for i in range(n):
        diag = abs(A[i, i]) #Mostly was able to understand, but used chatGPT to confirm last couple lines
        non_diag_sum = np.sum(np.abs(A[i])) - diag

        if diag < non_diag_sum:
            return False

    return True



#Matrix test 1. This one is not diagonally dominant.
A = np.array([
    [1, 5, 1],
    [7, 3, 1],
    [1, 6, 2]
])

print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(A)}")
print(A)


#Matrix test 2. This one is diagonally dominant.
B = np.array([
    [15, 3, 1],
    [2, 10, 2],
    [1, 2, 20]
])

print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(B)}")
print(B)


Is the matrix diagonally dominant? False
[[1 5 1]
 [7 3 1]
 [1 6 2]]
Is the matrix diagonally dominant? True
[[15  3  1]
 [ 2 10  2]
 [ 1  2 20]]
