In [1]:
import numpy as np


def gaussian_elimination(A, b):
    n = len(b) # number of equations
    # Making it into an upper triangle with zeros below
    for i in range(n):
        # Finding the row with the largest numbers to start dividing
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]

        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
# State value for one variable and then sub in to find other ones
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x


# Using the made function
A = [[3, 2, -4], [2, 3, 3], [5, -3, 1]]
b = [3, 15, 14]

solution = gaussian_elimination([row[:] for row in A], b[:]) #GPT used for cleaner decimal output
solution = [round(x, 6) for x in solution]
print(solution) 

[3.0, 1.0, 2.0]


In [2]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the diagonal
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")

            factor = U[j, i] / U[i, i] # Multiplier for row operation
            L[j, i] = factor # Store multiplier in L
            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    return L, U



A = np.array([[2, 3, 1], [4, 7, 5], [6, 18, 19]])

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7  5]
 [ 6 18 19]]
Lower Triangular Matrix L:
 [[1. 0. 0.]
 [2. 1. 0.]
 [3. 9. 1.]]
Upper Triangular Matrix U:
 [[  2.   3.   1.]
 [  0.   1.   3.]
 [  0.   0. -11.]]
