In [2]:
#Note: The Jacobi does not connverge, but the gauss-seidel function does.  


import numpy as np
import time



A=np.array([
[0.582745,0.48,0.10,0.0,0.0],
[0.48,1.044129,0.46,0.10,0.0],
[0.10,0.46,1.10431,0.44,0.10],
[0.0,0.10,0.44,0.963889,0.42],
[0.0,0.0,0.10,0.42,0.522565]
],dtype=float)

b=np.array([1.162745,2.084129,2.20431,1.923889,1.042565],dtype=float)

x0 = np.zeros(5)
tolerance = 1e-6
max_iterations = 100



def jacobi(A, b, x0, tolerance, max_iterations): #jacobi function from the power point slides
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tolerance:
            return x_new, k + 1, errors
        x = x_new
    return x, max_iterations, errors



def gauss_seidel(A, b, x0, tolerance, max_iterations): #gauss-seidel function from the power point slides
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tolerance:
            return x_new, k + 1, errors
        x = x_new
    return x, max_iterations, errors



# google forums and chatGPT used for the run time code
start = time.perf_counter() 
x_j, it_j, err_j = jacobi(A, b, x0, tolerance, max_iterations)
end = time.perf_counter()
jacobi_time = end - start

start = time.perf_counter()
x_gs, it_gs, err_gs = gauss_seidel(A, b, x0, tolerance, max_iterations)
end = time.perf_counter()
gs_time = end - start



print("Tolerance =", tolerance, "\n")

print("Jacobi:")
print("Solution:", x_j)
print(f"Iterations: {it_j}")
print(f"Runtime: {jacobi_time:.6e} seconds\n")

print("Gauss-Seidel:")
print("Solution:", x_gs)
print(f"Iterations: {it_gs}")
print(f"Runtime: {gs_time:.6e} seconds")

Tolerance = 1e-06 

Jacobi:
Solution: [0.34253948 0.34219824 0.34215212 0.34233398 0.34277892]
Iterations: 100
Runtime: 6.949728e-03 seconds

Gauss-Seidel:
Solution: [0.99999926 1.00000045 0.99999989 0.99999997 1.00000005]
Iterations: 21
Runtime: 1.328681e-03 seconds


In [3]:
#Note: The Jacobi does not connverge, but the gauss-seidel function does.  



import numpy as np
import time



A = np.array([[1, 1],
              [1, 1.0001]], dtype=float)
b = np.array([1, 1], dtype=float)

x0 = np.zeros(5)
tolerance = 1e-6
max_iterations = 100



def jacobi(A, b, x0, tolerance, max_iterations): #jacobi function from the power point slides
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tolerance:
            return x_new, k + 1, errors
        x = x_new
    return x, max_iterations, errors



def gauss_seidel(A, b, x0, tolerance, max_iterations): #gauss-seidel function from the power point slides
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tolerance:
            return x_new, k + 1, errors
        x = x_new
    return x, max_iterations, errors



# google forums and chatGPT used for the run time code
start = time.perf_counter() 
x_j, it_j, err_j = jacobi(A, b, x0, tolerance, max_iterations)
end = time.perf_counter()
jacobi_time = end - start

start = time.perf_counter()
x_gs, it_gs, err_gs = gauss_seidel(A, b, x0, tolerance, max_iterations)
end = time.perf_counter()
gs_time = end - start



print("Tolerance =", tolerance, "\n")

print("Jacobi:")
print("Solution:", x_j)
print(f"Iterations: {it_j}")
print(f"Runtime: {jacobi_time:.6e} seconds\n")

print("Gauss-Seidel:")
print("Solution:", x_gs)
print(f"Iterations: {it_gs}")
print(f"Runtime: {gs_time:.6e} seconds")

Tolerance = 1e-06 

Jacobi:
Solution: [0.00498727 0.         0.         0.         0.        ]
Iterations: 100
Runtime: 9.037685e-03 seconds

Gauss-Seidel:
Solution: [1. 0. 0. 0. 0.]
Iterations: 2
Runtime: 3.264342e-04 seconds


In [4]:
#Note: Neither converge  



import numpy as np
import time



A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])


x0 = np.zeros(5)
tolerance = 1e-6
max_iterations = 100



def jacobi(A, b, x0, tolerance, max_iterations): #jacobi function from the power point slides
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tolerance:
            return x_new, k + 1, errors
        x = x_new
    return x, max_iterations, errors



def gauss_seidel(A, b, x0, tolerance, max_iterations): #gauss-seidel function from the power point slides
    n = len(b)
    x = x0.copy()
    errors = []
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        error = np.linalg.norm(x_new - x, ord=np.inf)
        errors.append(error)
        if error < tolerance:
            return x_new, k + 1, errors
        x = x_new
    return x, max_iterations, errors



# google forums and chatGPT used for the run time code
start = time.perf_counter() 
x_j, it_j, err_j = jacobi(A, b, x0, tolerance, max_iterations)
end = time.perf_counter()
jacobi_time = end - start

start = time.perf_counter()
x_gs, it_gs, err_gs = gauss_seidel(A, b, x0, tolerance, max_iterations)
end = time.perf_counter()
gs_time = end - start



print("Tolerance =", tolerance, "\n")

print("Jacobi:")
print("Solution:", x_j)
print(f"Iterations: {it_j}")
print(f"Runtime: {jacobi_time:.6e} seconds\n")

print("Gauss-Seidel:")
print("Solution:", x_gs)
print(f"Iterations: {it_gs}")
print(f"Runtime: {gs_time:.6e} seconds")

Tolerance = 1e-06 

Jacobi:
Solution: [0.         0.00498727 0.         0.         0.        ]
Iterations: 100
Runtime: 4.452532e-03 seconds

Gauss-Seidel:
Solution: [0.99014933 0.00994967 0.         0.         0.        ]
Iterations: 100
Runtime: 3.456913e-03 seconds


In [11]:
import numpy as np

def is_diagonally_dominant(A): #define the diagonal check function
    A = np.array(A)
    n = A.shape[0]

    for i in range(n):
        diag = abs(A[i, i]) #Mostly was able to understand, but used chatGPT to confirm last couple lines
        non_diag_sum = np.sum(np.abs(A[i])) - diag

        if diag < non_diag_sum:
            return False

    return True



#Matrix test 1. This one is not diagonally dominant.
A = np.array([
    [1, 5, 1],
    [7, 3, 1],
    [1, 6, 2]
])

print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(A)}")
print(A)


#Matrix test 2. This one is diagonally dominant.
B = np.array([
    [15, 3, 1],
    [2, 10, 2],
    [1, 2, 20]
])

print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(B)}")
print(B)

Is the matrix diagonally dominant? False
[[1 5 1]
 [7 3 1]
 [1 6 2]]
Is the matrix diagonally dominant? True
[[15  3  1]
 [ 2 10  2]
 [ 1  2 20]]
