In [1]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [4]:
v_add = v1 + v2


dot_product = np.dot(v1, v2)

print(dot_product)

32


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

print()

B = np.array([[7, 8, 9], [10, 11,12], [13, 14, 15]])
print(B)

print()

transpose_A = A.T
print(transpose_A)

x = np.linalg.

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[1 4]
 [2 5]
 [3 6]]
